name: Auto actualizar precios

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    name: Actualizar precios de tabacos
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repo
        uses: actions/checkout@v4

      - name: Instalar NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20.3.0

      - name: Instalar dependencias
        run: npm install

      - name: Obtener lista completa de tabacos (CSV)
        run: bash get-tobaccos.sh

      - name: Obtener nuevos BOEs
        run: npm run boe

      - name: Extraer precios de los BOEs
        run: npm run parse

      - name: Enriquecer con propiedades de tabacos
        run: npm run enrich

      - name: Guardar cambios
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'chore: actualizados precios de tabacos de pipa'
          add: 'public data'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
